name: Composer outdated

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "30 1 * * *"

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
        outdated-args: [ '--ignore=phpunit/phpunit' ]
        include:
          - php: '7.4'
            outdated-args: '--ignore=nette/finder --ignore=phpunit/phpunit'

    name: Composer outdated - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: Composer outdated
        run: composer outdated -D --strict ${{ matrix.outdated-args }}
