name: PHPunit with lowest dependencies

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "30 1 * * *"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]

    name: PHPunit with lowest dependencies - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --prefer-lowest --no-progress --no-interaction

      - name: PHPunit
        run: vendor/bin/phpunit --coverage-text

      - name: Debugging artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: compiled-templates-lowest-php${{ matrix.php }}
          path: |
            tmp/phpstan-latte
