name: PHPunit with lowest dependencies

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    name: PHPunit with lowest dependencies - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --prefer-lowest --no-progress --no-interaction

      - name: PHPunit
        run: vendor/bin/phpunit --coverage-text
