name: PHP syntax checker

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "30 1 * * *"

jobs:
  syntax_checker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]

    name: PHP syntax checker - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      - name: Check syntax
        run: find src tests -name "*.php" ! -name "engine.bootstrap-firstClassCallableFilter.php" ! -name "EnumSomething.php" -print0 | xargs -0 -n1 -P8 php -l

  syntax_checker-81plus:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3' ]

    name: PHP syntax checker - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      - name: Check syntax
        run: find src tests -name "engine.bootstrap-firstClassCallableFilter.php" ! -name "EnumSomething.php" -print0 | xargs -0 -n1 -P8 php -l
